/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.forme;

import garaza.Garaza;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.FileHandler;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import vozilo.Vozilo;
import platforma.Platforma;
import platforma.Polje;

/**
 *
 * @author djord
 */
public class AdministratorForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    //private AddVehicleForm dodajVoziloForm = null;
    Garaza garaza = new Garaza();
    int trenutnaPlatforma;
    public static boolean usaoUIzmjenu = false;

    public int getTrenutnaPlatforma() {
        return trenutnaPlatforma;
    }
    private int tipVozila;

    public AdministratorForm() {
        initComponents();
        setLocationRelativeTo(null);
        setCmbPlatforma();
        setTable(); // razmisli jos da li ovako
        //Garaza.printGaraza();
        this.setTitle("Garaza");
        this.setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
    }

    private void setCmbPlatforma() {
        for (Integer i = 0; i < Garaza.getBrojPlatformi(); i++) {
            cmbPlatforma.addItem("Platforma " + i.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bAdd = new javax.swing.JButton();
        bChange = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmbPlatforma = new javax.swing.JComboBox<String>();
        lObavjestenja = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bExitAdmin = new javax.swing.JButton();
        bUserPart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cmbTipVozila = new javax.swing.JComboBox<String>();
        lObavjestenje1 = new javax.swing.JLabel();
        lObavjestenje2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Dodaj");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 40, 37, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Izmjeni");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 100, 43, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Izbrisi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 160, 33, 17);

        bAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/slike/addVehicle.png"))); // NOI18N
        bAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAdd.setPreferredSize(new java.awt.Dimension(48, 48));
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });
        jPanel1.add(bAdd);
        bAdd.setBounds(80, 10, 48, 48);

        bChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/slike/changeVehicle.png"))); // NOI18N
        bChange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bChange.setMaximumSize(new java.awt.Dimension(48, 48));
        bChange.setMinimumSize(new java.awt.Dimension(48, 48));
        bChange.setPreferredSize(new java.awt.Dimension(48, 48));
        bChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChangeActionPerformed(evt);
            }
        });
        jPanel1.add(bChange);
        bChange.setBounds(80, 70, 50, 50);

        bDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/slike/deleteVehicle.png"))); // NOI18N
        bDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDelete.setPreferredSize(new java.awt.Dimension(48, 48));
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(bDelete);
        bDelete.setBounds(80, 130, 50, 50);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Platforma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setMinimumSize(new java.awt.Dimension(180, 140));
        jPanel3.setLayout(null);

        cmbPlatforma.setMaximumRowCount(3);
        cmbPlatforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPlatformaActionPerformed(evt);
            }
        });
        jPanel3.add(cmbPlatforma);
        cmbPlatforma.setBounds(10, 20, 100, 20);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(350, 40, 120, 140);

        lObavjestenja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lObavjestenja.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Informacije", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(lObavjestenja);
        lObavjestenja.setBounds(480, 40, 300, 140);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 210, 640, 270);

        bExitAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/slike/exitbutton.png"))); // NOI18N
        bExitAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bExitAdmin.setPreferredSize(new java.awt.Dimension(48, 57));
        bExitAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitAdminActionPerformed(evt);
            }
        });
        jPanel1.add(bExitAdmin);
        bExitAdmin.setBounds(10, 420, 50, 50);

        bUserPart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/slike/playbutton.png"))); // NOI18N
        bUserPart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bUserPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUserPartActionPerformed(evt);
            }
        });
        jPanel1.add(bUserPart);
        bUserPart.setBounds(740, 420, 50, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Pokreni");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(740, 480, 80, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("IZLAZ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 480, 50, 17);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Tip vozila", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setLayout(null);

        cmbTipVozila.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbTipVozila.setMaximumRowCount(6);
        cmbTipVozila.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Motocikl", "Automobil", "Kombi", "Policijski automobil", "Policijski kombi", "Policijski motocikl", "Vatrogasni kombi", "Sanitetski kombi", "Sanitetski automobil" }));
        cmbTipVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipVozilaActionPerformed(evt);
            }
        });
        jPanel5.add(cmbTipVozila);
        cmbTipVozila.setBounds(10, 20, 140, 23);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(170, 40, 160, 140);

        lObavjestenje1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lObavjestenje1);
        lObavjestenje1.setBounds(490, 60, 290, 30);

        lObavjestenje2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lObavjestenje2);
        lObavjestenje2.setBounds(490, 100, 280, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        tipVozila = cmbTipVozila.getSelectedIndex();
        DodajVoziloForm dodajVoziloForm = new DodajVoziloForm(tipVozila, trenutnaPlatforma, this);

        dodajVoziloForm.setLocationRelativeTo(null);
        dodajVoziloForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bAddActionPerformed

    private void cmbPlatformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlatformaActionPerformed
        trenutnaPlatforma = Integer.parseInt(cmbPlatforma.getSelectedItem().toString().split(" ")[1]);
        setTable();
    }//GEN-LAST:event_cmbPlatformaActionPerformed

    private void bExitAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitAdminActionPerformed
        try {
            Garaza.serijalizacija();
        } catch (IOException ex) {
            Logger.getLogger(AdministratorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_bExitAdminActionPerformed

    private void cmbTipVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipVozilaActionPerformed

    }//GEN-LAST:event_cmbTipVozilaActionPerformed

    private void bUserPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUserPartActionPerformed
        try {
            Garaza.serijalizacija();
        } catch (IOException ex) {
            Logger.getLogger(AdministratorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        KorisnikForm korisnikForm = new KorisnikForm();
        korisnikForm.setVisible(true);
        this.setVisible(false);
        korisnikForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_bUserPartActionPerformed

    public void setTable() {
        String[] kolone = {"Naziv vozila", "Registarski broj", "Parking mjesto", "Tip vozila", "Vrijeme parkiranja"};
        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(garaza.prikazTrenutnePlatforme(trenutnaPlatforma), kolone) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
        this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);
        this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(20);
        this.jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
        this.jTable1.getColumnModel().getColumn(4).setPreferredWidth(140);
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getRowCount() == 0 || jTable1.getSelectionModel().isSelectionEmpty()) {
            return;
        }
        String registarskiBrojIzabranogVozila = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1).toString();
        Vozilo vozilo = Garaza.getVozilo(trenutnaPlatforma, registarskiBrojIzabranogVozila);
        this.tipVozila = vozilo.getTipVozila();
        lObavjestenja.setText("");
        lObavjestenje1.setText("Broj sasije: " + vozilo.getBrojSasije());
        lObavjestenje2.setText("Broj motora: " + vozilo.getBrojMotora());
        try {
            if (vozilo == null) {
                return;
            }
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_jTable1MouseClicked

    String registarskiBrojIzabranogVozila;
    private void bChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChangeActionPerformed
        usaoUIzmjenu = true;
        if (jTable1.getRowCount() == 0) {
            return;
        }
        if (jTable1.getSelectionModel().isSelectionEmpty()) {
            return;
        }
        registarskiBrojIzabranogVozila = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1).toString();
        IzmjeniVoziloForm izmjeniVoziloForm = new IzmjeniVoziloForm(tipVozila, trenutnaPlatforma, this);
        this.setVisible(false);
        izmjeniVoziloForm.setVisible(true);
        izmjeniVoziloForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_bChangeActionPerformed

    public String getRegistarskiBrojIzabranogVozila() {
        return registarskiBrojIzabranogVozila;
    }

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        if (this.jTable1.getRowCount() == 0 || this.jTable1.getSelectionModel().isSelectionEmpty()) {
            return;
        }
        String registarskiBrojIzabranogVozila = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1).toString();
        garaza.izbrisiVozilo(trenutnaPlatforma, registarskiBrojIzabranogVozila);
        setTable();
    }//GEN-LAST:event_bDeleteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Garaza.serijalizacija();
        } catch (IOException ex) {
            Logger.getLogger(AdministratorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Handler handler = null;
        try {
            handler = new FileHandler("./error.log");
            Logger.getLogger("").addHandler(handler);
        } catch (IOException | SecurityException ex) {
            Logger.getLogger(AdministratorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bChange;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bExitAdmin;
    private javax.swing.JButton bUserPart;
    private javax.swing.JComboBox<String> cmbPlatforma;
    private javax.swing.JComboBox<String> cmbTipVozila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lObavjestenja;
    private javax.swing.JLabel lObavjestenje1;
    private javax.swing.JLabel lObavjestenje2;
    // End of variables declaration//GEN-END:variables
}
