/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.forme;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import vozilo.Automobil;
import vozilo.Kombi;
import vozilo.Vozilo;

/**
 *
 * @author djord
 */
public class IzmjeniVoziloForm extends DodajVoziloForm {

    /**
     * Creates new form ChangeVehicleForm
     */
    public IzmjeniVoziloForm() {
        initComponents();
                this.setTitle("Garaza");
        this.setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
    }

    public IzmjeniVoziloForm(int tipVozila, int brojPlatforme, AdministratorForm adminForm) {

        super(tipVozila, brojPlatforme, adminForm);
        Vozilo vozilo = adminForm.garaza.getVozilo(adminForm.trenutnaPlatforma, adminForm.getRegistarskiBrojIzabranogVozila());
        //adminForm.garaza.izbrisiVozilo(brojPlatforme, vozilo.getRegistarskiBroj()); baca null pa rjesi u dodaj
        super.getTfNazivVozila().setText(vozilo.getNaziv());
        super.getTfBrojMotoraVozila().setText(vozilo.getBrojMotora());
        super.getTfBrojSasijeVozila().setText(vozilo.getBrojSasije());
        super.getTfRegistarskiBrojVozila().setText(vozilo.getRegistarskiBroj());
        super.file = vozilo.getFotografija();

        System.out.println("FILE PATH: " + file.getPath());
        if (file != null) {
            String s = "/slikeVozila/" + file.getName().intern();
            try {
                Thread.sleep(2000);
            } catch (Exception ex) {
            }

            ImageIcon imageIcon = new ImageIcon(getClass().getResource(s));
            Image image = imageIcon.getImage();
            Image newimg = image.getScaledInstance(215, 276, java.awt.Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(newimg);
            super.getlFotografijaVozila().setIcon(imageIcon);
        }
        //lFotografijaVozila.setIcon(imageIcon);

       // super.getlFotografijaVozila().setIcon(imageIcon);
        System.out.println("SUPER FILE: " + super.file);

        if (vozilo instanceof Automobil) {
            super.getTfBrojVrata().setText(Integer.toString(((Automobil) vozilo).getBrojVrata()));
        } else if (vozilo instanceof Kombi) {
            super.getTfNosivost().setText(Double.toString(((Kombi) vozilo).getNosivost()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
