/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.forme;

import garaza.Garaza;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author djord
 */
public class KorisnikForm extends javax.swing.JFrame {

    /**
     * Creates new form UserForm
     */
    int brojVozila;

    public KorisnikForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfBrojVozila = new javax.swing.JTextField();
        bPokreniSimulaciju = new javax.swing.JButton();
        lObavjestenja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Unesite minimalan broj vozila");

        bPokreniSimulaciju.setText("Pokreni simulaciju");
        bPokreniSimulaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPokreniSimulacijuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bPokreniSimulaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBrojVozila, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lObavjestenja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1)
                        .addGap(0, 119, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lObavjestenja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(149, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfBrojVozila, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bPokreniSimulaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(81, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPokreniSimulacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPokreniSimulacijuActionPerformed
        try {
            brojVozila = Integer.parseInt(tfBrojVozila.getText());

            if (brojVozila < 0 || brojVozila > 28) {
                lObavjestenja.setText("Nekorektan unos!");
                tfBrojVozila.setText("");
                return;
            }
        } catch (Exception ex) {
            lObavjestenja.setText("Nekorektan unos!");
            //Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        for (int i = 0; i < Garaza.getBrojPlatformi(); i++) {
            if (brojVozila < Garaza.getBrojVozilaSaPlatforme(i)) {
                lObavjestenja.setText("Nekorektan unos!");
                return;
            }
        }
        SimulacijaForm simulacijaForm = new SimulacijaForm(brojVozila);
        simulacijaForm.setVisible(true);
        simulacijaForm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_bPokreniSimulacijuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPokreniSimulaciju;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lObavjestenja;
    private javax.swing.JTextField tfBrojVozila;
    // End of variables declaration//GEN-END:variables
}
